version: "3"

services:
  server_web:
    container_name: Server_Website
    restart: always
    build:
      context: ./Website
      dockerfile: Dockerfile
    volumes:
      - ./Website/:/app
      - /app/node_modules
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  server_api:
    container_name: Server_API
    restart: always
    build:
      context: ./Server
      dockerfile: Dockerfile
    volumes:
      - ./Server/:/app
    ports:
      - "5423:${API_PORT}"
    depends_on:
      - db
    networks:
      - db-api-network

  db:
    container_name: PostgreSQL
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db-api-network

networks:
  db-api-network:
    driver: bridge
